[package]
name = "lorem-ipsum-rs"
version = "0.1.0"
description = "a library providing a proc-macro for lorem ipsum placeholder text"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

